//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactTracing.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContactTracing.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT PROJECTS.
        /// </summary>
        public static string CurrentProjects {
            get {
                return ResourceManager.GetString("CurrentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To open an existing project, choose appropriate region and language settings on the left..
        /// </summary>
        public static string Instructions3 {
            get {
                return ResourceManager.GetString("Instructions3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check ✓ if seen and healthy.
        /// </summary>
        public static string LegendRow1 {
            get {
                return ResourceManager.GetString("LegendRow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check ✗ if seen and sick. If sick, write symptoms under Notes..
        /// </summary>
        public static string LegendRow2 {
            get {
                return ResourceManager.GetString("LegendRow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check – if not seen..
        /// </summary>
        public static string LegendRow3 {
            get {
                return ResourceManager.GetString("LegendRow3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check NR if no information was recorded..
        /// </summary>
        public static string LegendRow4 {
            get {
                return ResourceManager.GetString("LegendRow4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOADING....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW OUTBREAK.
        /// </summary>
        public static string NewOutbreakTitle {
            get {
                return ResourceManager.GetString("NewOutbreakTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTBREAK SETTINGS.
        /// </summary>
        public static string OutbreakSettingsTitle {
            get {
                return ResourceManager.GetString("OutbreakSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First-level (largest) administrative location label. This is the location that the application will use to calculate location-based case counts..
        /// </summary>
        public static string SettingsAdm1Description {
            get {
                return ResourceManager.GetString("SettingsAdm1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second-level administrative location label:.
        /// </summary>
        public static string SettingsAdm2Description {
            get {
                return ResourceManager.GetString("SettingsAdm2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-level administrative location label:.
        /// </summary>
        public static string SettingsAdm3Description {
            get {
                return ResourceManager.GetString("SettingsAdm3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth-level (smallest) administrative location label. This is intended to be a village/town level location..
        /// </summary>
        public static string SettingsAdm4Description {
            get {
                return ResourceManager.GetString("SettingsAdm4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string SettingsCountry {
            get {
                return ResourceManager.GetString("SettingsCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Outbreak Detection:.
        /// </summary>
        public static string SettingsDetectedDate {
            get {
                return ResourceManager.GetString("SettingsDetectedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbreak Case ID Pattern:.
        /// </summary>
        public static string SettingsIDPattern {
            get {
                return ResourceManager.GetString("SettingsIDPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbreak Case ID Prefix:.
        /// </summary>
        public static string SettingsIDPrefix {
            get {
                return ResourceManager.GetString("SettingsIDPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbreak Case ID Separator (if any):.
        /// </summary>
        public static string SettingsIDSep {
            get {
                return ResourceManager.GetString("SettingsIDSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbreak Name:.
        /// </summary>
        public static string SettingsOutbreakName {
            get {
                return ResourceManager.GetString("SettingsOutbreakName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project File Name:.
        /// </summary>
        public static string SettingsProjectName {
            get {
                return ResourceManager.GetString("SettingsProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Short Case Form.
        /// </summary>
        public static string SettingsUseShortForm {
            get {
                return ResourceManager.GetString("SettingsUseShortForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virus:.
        /// </summary>
        public static string SettingsVirus {
            get {
                return ResourceManager.GetString("SettingsVirus", resourceCulture);
            }
        }
    }
}
