//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactTracing.LabView.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContactTracing.LabView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Case.
        /// </summary>
        public static string AddCase {
            get {
                return ResourceManager.GetString("AddCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed Acute.
        /// </summary>
        public static string AnalysisClassConfirmedAcute {
            get {
                return ResourceManager.GetString("AnalysisClassConfirmedAcute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed Convalescent.
        /// </summary>
        public static string AnalysisClassConfirmedConvalescent {
            get {
                return ResourceManager.GetString("AnalysisClassConfirmedConvalescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeterminate.
        /// </summary>
        public static string AnalysisClassIndeterminate {
            get {
                return ResourceManager.GetString("AnalysisClassIndeterminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs Follow-up Sample.
        /// </summary>
        public static string AnalysisClassNeedsFollowUp {
            get {
                return ResourceManager.GetString("AnalysisClassNeedsFollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative, Needs Follow-up Sample.
        /// </summary>
        public static string AnalysisClassNegativeNeedsFollowUp {
            get {
                return ResourceManager.GetString("AnalysisClassNegativeNeedsFollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a Case.
        /// </summary>
        public static string AnalysisClassNotCase {
            get {
                return ResourceManager.GetString("AnalysisClassNotCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Sampled.
        /// </summary>
        public static string AnalysisClassNotSampled {
            get {
                return ResourceManager.GetString("AnalysisClassNotSampled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results Pending.
        /// </summary>
        public static string AnalysisClassResultsPending {
            get {
                return ResourceManager.GetString("AnalysisClassResultsPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string ColHeaderAge {
            get {
                return ResourceManager.GetString("ColHeaderAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of
        ///Death.
        /// </summary>
        public static string ColHeaderDateDeath {
            get {
                return ResourceManager.GetString("ColHeaderDateDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Sample
        ///Collected.
        /// </summary>
        public static string ColHeaderDateSampleCollected {
            get {
                return ResourceManager.GetString("ColHeaderDateSampleCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Sample
        ///Tested.
        /// </summary>
        public static string ColHeaderDateSampleTested {
            get {
                return ResourceManager.GetString("ColHeaderDateSampleTested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Acute.
        /// </summary>
        public static string ColHeaderDaysAcute {
            get {
                return ResourceManager.GetString("ColHeaderDaysAcute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string ColHeaderDistrict {
            get {
                return ResourceManager.GetString("ColHeaderDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Lab
        ///Classification.
        /// </summary>
        public static string ColHeaderFinalLabClass {
            get {
                return ResourceManager.GetString("ColHeaderFinalLabClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Lab
        ///Specimen ID.
        /// </summary>
        public static string ColHeaderFLSID {
            get {
                return ResourceManager.GetString("ColHeaderFLSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string ColHeaderGender {
            get {
                return ResourceManager.GetString("ColHeaderGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbreak Case
        ///ID.
        /// </summary>
        public static string ColHeaderID {
            get {
                return ResourceManager.GetString("ColHeaderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaria
        ///Rapid Test.
        /// </summary>
        public static string ColHeaderMRT {
            get {
                return ResourceManager.GetString("ColHeaderMRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Symptom
        ///Onset.
        /// </summary>
        public static string ColHeaderOnsetDate {
            get {
                return ResourceManager.GetString("ColHeaderOnsetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Names.
        /// </summary>
        public static string ColHeaderOtherNames {
            get {
                return ResourceManager.GetString("ColHeaderOtherNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Interpretation.
        /// </summary>
        public static string ColHeaderSampleInterpretation {
            get {
                return ResourceManager.GetString("ColHeaderSampleInterpretation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Type.
        /// </summary>
        public static string ColHeaderSampleType {
            get {
                return ResourceManager.GetString("ColHeaderSampleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-County.
        /// </summary>
        public static string ColHeaderSubCounty {
            get {
                return ResourceManager.GetString("ColHeaderSubCounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string ColHeaderSurname {
            get {
                return ResourceManager.GetString("ColHeaderSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Village.
        /// </summary>
        public static string ColHeaderVillage {
            get {
                return ResourceManager.GetString("ColHeaderVillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Summary.
        /// </summary>
        public static string DailySummary {
            get {
                return ResourceManager.GetString("DailySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Epi.
        /// </summary>
        public static string ExportToEpi {
            get {
                return ResourceManager.GetString("ExportToEpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to File.
        /// </summary>
        public static string ExportToFile {
            get {
                return ResourceManager.GetString("ExportToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAILY LAB SUMMARY.
        /// </summary>
        public static string HTMLDailyLabSummaryHeading {
            get {
                return ResourceManager.GetString("HTMLDailyLabSummaryHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string HTMLDate {
            get {
                return ResourceManager.GetString("HTMLDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To open an existing outbreak database, left-click the &quot;New Outbreak&quot; button below..
        /// </summary>
        public static string Instructions1 {
            get {
                return ResourceManager.GetString("Instructions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To open existing outbreak data, left-click on the desired outbreak in the Current Projects list to the right..
        /// </summary>
        public static string Instructions2 {
            get {
                return ResourceManager.GetString("Instructions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratory Database.
        /// </summary>
        public static string LaboratoryDatabaseHeading {
            get {
                return ResourceManager.GetString("LaboratoryDatabaseHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative.
        /// </summary>
        public static string Negative {
            get {
                return ResourceManager.GetString("Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Outbreak.
        /// </summary>
        public static string NewOutbreak {
            get {
                return ResourceManager.GetString("NewOutbreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive.
        /// </summary>
        public static string Positive {
            get {
                return ResourceManager.GetString("Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project with this name already exists. Please try again..
        /// </summary>
        public static string ProjectNameExistsTryAgain {
            get {
                return ResourceManager.GetString("ProjectNameExistsTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-mortem heart blood.
        /// </summary>
        public static string SampleTypeHeartBlood {
            get {
                return ResourceManager.GetString("SampleTypeHeartBlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string SampleTypeOther {
            get {
                return ResourceManager.GetString("SampleTypeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serum.
        /// </summary>
        public static string SampleTypeSerum {
            get {
                return ResourceManager.GetString("SampleTypeSerum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin biopsy.
        /// </summary>
        public static string SampleTypeSkin {
            get {
                return ResourceManager.GetString("SampleTypeSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole blood.
        /// </summary>
        public static string SampleTypeWholeBlood {
            get {
                return ResourceManager.GetString("SampleTypeWholeBlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
